apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc-1
  namespace: default
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
